### PR TITLE
MVC Example for Sencha Touch 2.1

### PR DESCRIPTION
**Pull request by pherris**
Had to include your code in the jslib/dir in my example (so it will be duplicated in the repo if you accept these changes). I did generate the sub-directory with the Sencha Cmd 3.x utilities and I did test that I can build the app for production successfully.

### CODE REVIEW

**Comment by mitchellsimoens** [comment]
merge conflicts. What is the purpose of this example also?

**Comment by pherris** [comment]
The MVC example wasnt working for me or some others (https://github.com/mitchellsimoens/Ext.ux.touch.grid/issues/38) so I built it back up here.

**Comment by mitchellsimoens** [comment]
Is the MVC example back to working then?

**Comment by pherris** [comment]
yes, it was when I checked it in :)

**Pull request closed without merging**
